# -*- coding: utf-8 -*-
# Deployment settings for GameThriveExample.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Applications/Marmalade.app/Contents/s3e/makefile_builder/mkb.py', '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/GameThriveExample.mkb', '--deploy-only', '--hub-data', '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/project_GameThriveExample/mkb-osx.txt', '--buildenv=XCODE']
mkb = '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/GameThriveExample.mkb'
mkf = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/s3eGameThrive.mkf', '/Applications/Marmalade.app/Contents/modules/iwutil/iwutil.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libjpeg/libjpeg.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libpng/libpng.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/zlib/zlib.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'GameThriveExample'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'GameThriveExample'
    long_caption = 'GameThriveExample'
    version = [0, 0, 1]
    config = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/data/app.icf']
    data_dir = '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/data'
    iphone_link_lib = ['s3eGameThrive']
    osx_ext_dll = []
    ws8_ext_capabilities = []
    android_external_res = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/incoming/android/res']
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/lib/iphone']
    android_extra_application_manifest = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/extras.application.txt']
    ws8_ext_native_dll = []
    blackberry_extra_descriptor = []
    android_extra_manifest = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/extras.manifest.txt', '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/GameThriveExtraManifest.xml']
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws81_ext_sdk_ref_file = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/incoming/android/GameThriveSDK.jar', '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/lib/android/s3eGameThrive.jar', '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/incoming/android/google-play-services.jar', '/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/incoming/android/android-support-v4.jar']
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = ['-weak_framework UIKit']
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = ['/Users/hiptic/Documents/GameThrive/SDK/Marmalade/extension/lib/android/libGameThrive.so']
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'x86' : {
                   'debug'   : r'/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_xcode/build/Debug/GameThriveExample.s86',
                   'release' : r'/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_xcode/build/Release/GameThriveExample.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_xcode/build/Debug ARM/GameThriveExample.s3e',
                   'release' : r'/Users/hiptic/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_xcode/build/Release ARM/GameThriveExample.s3e',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
