/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGAMETHRIVE_AUTODEFS_H
#define S3EGAMETHRIVE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GAMETHRIVE_NAME "s3eGameThrive"
#define S3E_EXT_GAMETHRIVE_HASH 0x4315377c

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eGameThrive", 11)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EGAMETHRIVE_AUTODEFS_H */
