/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eGameThrive_autodefs.h"
#include "s3eEdk.h"
#include "s3eGameThrive.h"
//Declarations of Init and Term functions
extern s3eResult s3eGameThriveInit();
extern void s3eGameThriveTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void GameThriveInitialize_wrap(const char* appId, const char* googleProjectNumber, GameThriveNotificationReceivedCallbackFn callbackFn, s3eBool autoRegister)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveInitialize"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveInitialize, 4, appId, googleProjectNumber, callbackFn, autoRegister);
}

static void GameThriveSendTag_wrap(const char* key, const char* value)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveSendTag"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveSendTag, 2, key, value);
}

static void GameThriveGetTags_wrap(GameThriveTagsReceivedCallbackFn callbackFn)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveGetTags"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveGetTags, 1, callbackFn);
}

static void GameThriveDeleteTag_wrap(const char* key)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveDeleteTag"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveDeleteTag, 1, key);
}

static void GameThriveSendPurchase_wrap(const double* amount)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveSendPurchase"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveSendPurchase, 1, amount);
}

static void GameThriveGetIdsAvailable_wrap(GameThriveIdsAvailableCallbackFn callbackFn)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveGetIdsAvailable"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveGetIdsAvailable, 1, callbackFn);
}

static int GameThriveSystemPaused_wrap(void* systemData, void* userData)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveSystemPaused"));
    return (int)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveSystemPaused, 2, systemData, userData);
}

static int GameThriveSystemResume_wrap(void* systemData, void* userData)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveSystemResume"));
    return (int)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveSystemResume, 2, systemData, userData);
}

static void GameThriveRegisterForPushNotifications_wrap()
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveRegisterForPushNotifications"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveRegisterForPushNotifications, 0);
}

static void GameThriveEnableVibrate_wrap(s3eBool enable)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveEnableVibrate"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveEnableVibrate, 1, enable);
}

static void GameThriveEnableSound_wrap(s3eBool enable)
{
    IwTrace(GAMETHRIVE_VERBOSE, ("calling s3eGameThrive func on main thread: GameThriveEnableSound"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GameThriveEnableSound, 1, enable);
}

#define GameThriveInitialize GameThriveInitialize_wrap
#define GameThriveSendTag GameThriveSendTag_wrap
#define GameThriveGetTags GameThriveGetTags_wrap
#define GameThriveDeleteTag GameThriveDeleteTag_wrap
#define GameThriveSendPurchase GameThriveSendPurchase_wrap
#define GameThriveGetIdsAvailable GameThriveGetIdsAvailable_wrap
#define GameThriveSystemPaused GameThriveSystemPaused_wrap
#define GameThriveSystemResume GameThriveSystemResume_wrap
#define GameThriveRegisterForPushNotifications GameThriveRegisterForPushNotifications_wrap
#define GameThriveEnableVibrate GameThriveEnableVibrate_wrap
#define GameThriveEnableSound GameThriveEnableSound_wrap

#endif

void s3eGameThriveRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[11];
    funcPtrs[0] = (void*)GameThriveInitialize;
    funcPtrs[1] = (void*)GameThriveSendTag;
    funcPtrs[2] = (void*)GameThriveGetTags;
    funcPtrs[3] = (void*)GameThriveDeleteTag;
    funcPtrs[4] = (void*)GameThriveSendPurchase;
    funcPtrs[5] = (void*)GameThriveGetIdsAvailable;
    funcPtrs[6] = (void*)GameThriveSystemPaused;
    funcPtrs[7] = (void*)GameThriveSystemResume;
    funcPtrs[8] = (void*)GameThriveRegisterForPushNotifications;
    funcPtrs[9] = (void*)GameThriveEnableVibrate;
    funcPtrs[10] = (void*)GameThriveEnableSound;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[11] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3eGameThrive", funcPtrs, sizeof(funcPtrs), flags, s3eGameThriveInit, s3eGameThriveTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eGameThriveStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eGameThriveRegisterExt;
    return 0;
}

int g_s3eGameThriveVal = s3eGameThriveStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eGameThriveRegisterExt();
}
#endif

#endif
