# -*- coding: utf-8 -*-
# Deployment settings for GameThriveExample.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.3/s3e/makefile_builder/mkb.py', 'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/GameThriveExample.mkb', '--deploy-only', '--hub-data', 'C:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/project_GameThriveExample/mkb-windows.txt', '--buildenv=VC12X']
mkb = 'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/GameThriveExample.mkb'
mkf = ['c:\\users\\kasten\\documents\\gamethrive\\sdk\\marmalade\\s3egamethrive\\s3egamethrive.mkf', 'c:\\marmalade\\7.3\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\zlib\\zlib.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'GameThriveExample'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'GameThriveExample'
    long_caption = 'GameThriveExample'
    version = [0, 0, 1]
    config = ['c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/data/app.icf']
    data_dir = 'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/data'
    iphone_link_lib = ['s3eGameThrive']
    osx_ext_dll = []
    ws8_ext_capabilities = []
    android_external_res = ['c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/incoming/android/res', 'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/android/res']
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/lib/iphone']
    android_extra_application_manifest = ['c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/extras.application.txt']
    ws8_ext_native_dll = []
    blackberry_extra_descriptor = []
    android_extra_manifest = ['c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/extras.manifest.txt', 'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/GameThriveExtraManifest.xml']
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws81_ext_sdk_ref_file = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = ['c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/incoming/android/GameThriveSDK.jar', 'c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/lib/android/s3eGameThrive.jar', 'c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/incoming/android/google-play-services.jar', 'c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/incoming/android/android-support-v4.jar']
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = ['-weak_framework UIKit']
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = ['c:/users/kasten/documents/gamethrive/sdk/marmalade/s3egamethrive/lib/android/libGameThrive.so']
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_gcc_x86/GameThriveExample.so',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_gcc_x86/GameThriveExample.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_gcc_x86_tizen/GameThriveExample.s86',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_gcc_x86_tizen/GameThriveExample.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_gcc_mips/GameThriveExample.so',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_gcc_mips/GameThriveExample.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_gcc_arm/GameThriveExample.s3e',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_gcc_arm/GameThriveExample.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_gcc_mips/GameThriveExample.so',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_gcc_mips/GameThriveExample.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_gcc_x86_android/GameThriveExample.so',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_gcc_x86_android/GameThriveExample.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_arm/GameThriveExample.s3e',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_arm/GameThriveExample.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Debug_GameThriveExample_VC12X_x86/GameThriveExample.s86',
                   'release' : r'c:/Users/Kasten/Documents/GameThrive/SDK/Marmalade/GameThriveExample/build_gamethriveexample_vc12x/Release_GameThriveExample_VC12X_x86/GameThriveExample.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
